---
name: Actions security
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: [.github/workflows/**]

jobs:
  # Actions security tries to keep your GitHub actions secure by following these simple rules:
  # - Check if no issues are found on your GitHub Actions
  # - Ensure that all GitHub Actions and reusable workflow are pinned using directly a commit SHA
  actions_security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Github Actions lint
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@e4e462350f03685cf66f0a5f2f0bc3aa5de2df02 # v4.0.2
